Economically advanced, democratic countries trade intensely and scrupulously avoid war with one another. This "modern economic peace" [@CoeND] is empirically striking, but stubbornly resistant to theoretical consensus. One family of theories holds that this peace is "democratic" in nature [@Oneal1997; @Schultz2001; @Russett2001; @Fearon2008]. Another maintains that "commercial" ties bind countries into pacific relations [@Angell1911; @Polachek1980; @Mansfield2000a; @Gartzke2001; @Gartzke2007; @Martin2008; @Hegre2010].^[For a complete survey, see @Gartzke2015.]

The flow of trade is highly sensitive to trade policy [@Anderson2004], which is set by governments with commercial objectives that vary as a function of their political regimes [@Milner2005; @Gawande2009; @Ossa2014]. These same governments make choices over security policy, and whether or not to engage in wars with their trading partners. Political regimes affect the degree of political bias in policymaking -- the extent to which policies favor the masses or a small political elite [@BuenodeMesquita2003; @Acemoglu2005; @Jackson2007]. This makes it difficult to interpret the stylized facts of the modern economic peace. Are the advanced democracies peaceful because of their deep trading relations? Or do their political institutions generate incentives for trade and peace simultaneously?

Here, I develop a theory of trade, war, and political bias, in which both trade and war are endogenous objects. Governments choose trade policies that affect trade flows and welfare in the international economy, and vary on the extent to which are biased toward the narrow interests of firms versus the broad interests of consumers. War is employed to institute regime change abroad, altering the preferences of foreign governments and their concomitant policy choices. Trade policy bargaining is conducted "in the shadow of power" [@Powell1999], with counterfactual wars shaping the policy choices that prevail in times of peace. The model marries literatures on intra-industry trade [@Krugman1980; @Venables1987], the political economy of trade policy [@Grossman1994; @Grossman1995; @Ossa2011; @Ossa2012], and bargaining and war [@Fearon1995].

Governments care about the trade policy choices of their trading partners because of market access externalities [@Ossa2011; @Ossa2012]. By imposing barriers to  market access (tariffs), governments (partially) exclude foreign firms from the domestic market, shifting profit opportunities from foreign to home firms.^[I consider tariffs as the only trade policy instrument available to governments in the model developed below. However, in principle, barriers to trade can take on many other forms.] If governments value the profit opportunities of their own firms, then they will care about the trade policy choices of foreign governments.

Because they prefer free trade, *low bias* governments that internalize the interests of consumers impose smaller externalities on their trading partners, and present these trading partners with fewer incentives to forcibly impose regime change (Proposition `` `r Pgamma` ``). This decreases the likelihood of war between low bias governments (Proposition `` `r Pwar` ``). To the extent that democracies approximate the low bias ideal, this provides an explanation for the "democratic" component of the modern economic peace. Because these low bias governments also impose smaller barriers to trade, low bias dyads also trade more than their high bias counterparts. Thus, a correlation between trade and peace emerges (spuriously) from the model (Proposition `` `r PeqTrade` ``).

```{r emp_wars, echo=FALSE, warning=FALSE, message=FALSE, fig.cap = "The modern economic peace. Data from @Marshall2002, @Barbieri2008, @Barbieri2009, @Sarkees2010, @Bolt2018. \\label{fig:emp_wars}", fig.height=8.5, dpi=750, cache=T}

source("../figs/emp_wars.R")

polityDensity + empty + main + tradeIntDensity + polityRail + empty + caption.a + empty + plot_layout(ncol=2, widths=c(8,1), heights=c(1,10,2,5))

```

This correlation can be seen in Figure \ref{fig:emp_wars}. Since 1870, democratic dyads have tended to be more deeply economically integrated than autocratic and mixed dyads. The also almost never fight wars with one another. The model provides an interpretation for this phenomenon, without assigning trade or conflict causal primacy. The modern economic peace emerges because democracies' trade policy *preferences* are compatible with the preferences of other democracies. This renders military power superfluous -- military coercion serves no purpose in relations between democracies. By contrast, the ideal trade policies of autocracies impose large externalities on other governments and generate incentives for coercive diplomacy.

The kind of military influence theorized here has been dubbed *gunboat diplomacy* [@Findlay2007]. The United States coerced trade policy concessions out of Japan in the 1850s through the Perry Expeditions, an instance in which its policy demands were clearly paired with a threat of military force. In the same period, Britain and France succeeded in forcing a recalcitrant Chinese government to open its markets in the Opium Wars (1839-1842; 1856-1860). In both cases, the target government held protectionist preferences and was forced to deviate from its ideal policies in order to appease a more militarily powerful adversary. The model provides a possible rationale for the relative dearth of such incidents in the post-World War II, more democratic era. Nevertheless, governments in the modern era still appear to employ overt and covert force to secure favorable commercial policy outcomes abroad [@Dube2011; @Berger2013].

In the model, governments value militaries for their ability to impose regime change. Puppet governments installed by governments victorious in wars have liberal trading preferences and allow victorious governments to secure previously unrealized market access. This is the threat point governments leverage in securing more favorable bilateral trade policy outcomes. When peaceful bargaining fails, regime change is employed instrumentally to change trade policy outcomes. This feature of the model provides a political-economic rationale for foreign-imposed regime change in world politics [@Owen2002; @Lo2008].

Latent government preferences over trade policy matter because they determine what policy each government would adopt in the absence of foreign military coercion. The need for regime change is obviated if a government will maintain completely open markets when uncoerced. Thus, two maximimally liberal (low bias) governments will find no rationale for conflict. I argue verbally that democracies are more likely to approximate the low bias ideal, due to the power their political institutions imbue in consumers (voters). I crudely embed this logic in the governments' preference structure, as in @Jackson2007. Because consumers benefit from liberal trade policies, they should be expected to punish politicians that implement such policies [@Grossman1996; @Kono2008b].^[For skeptical takes on these mechanisms, see @Guisinger2009 and @Betz2019.] This provides a check on the (often protectionist) influence of special interest groups [@Grossman1994]. "Bias" in the model developed here is also similar conceptually to the size of the selectorate in the model of @BuenodeMesquita2003. Several studies provide evidence that democracies indeed adopt more liberal trade policies than autocracies [@Goldberg1999; @Mansfield2000b; @Milner2005; @Gawande2009; @Gawande2015].^[See @Kono2006 and  @Queralt2015 for alternative conclusions.] To the extent that this argument holds, the results derived about the behavior of low bias governments extend to those of democratic governments, providing an account of the modern economic peace. 

Because it determines policy preferences, the governments' degree of political bias also structures the bargaining environment between them. Low bias governments experience small conflicts of interest with one another, because their policy preferences are largely harmonious. By contrast, high bias governments endeavor to implement high barriers to trade, imposing large externalities on one another and generating conflicts of interest. Workhorse models of international war take this conflict as given [@Fearon1995]. These models ask: *given a conflict of interest*, what prevents governments from resolving disputes peacefully?

In abstracting away from the exact nature of the dispute at hand, these models direct our attention away from the question of why international disputes emerge in the first place. What do governments want, and why do their objectives bring them into conflict with one another [@Moravcsik1997]? In the model presented here, governments value the welfare of firms and consumers within the economy. The size of the "pie" over which governments negotiate depends on the weight they place on the welfare of consumers relative to firms. When information about the costs of war is held privately, this variation in the stakes of the negotiation affects governments' war propensity. 

The classical approach to the study of trade and war holds that economic integration increases the opportunity costs of conflict, driving states toward more pacific international relations [@Polachek1980].^[This logic has been critiqued by @Morrow1999b and @Gartzke2001.] @Pollins1989b presents an alternative interpretation of the same empirical facts -- namely, that amicable political relations promote trade. The fundamental problem is that "contentious" economies featuring both exchange and predation are not reducible to their economic and military components. Rather, military capacity influences the pattern of exchange, and expectations about exchange influence how governments choose to employ their military capacity.^[See @Carroll2018 for a unified treatment of economic exchange and military predation in a "contentious" international economy.]

Even if militaries ceased to exist, international trade would not likely be free, because governments do not always value the gains from trade. As @Gawande2009 show, many governments’ observed trade policy behavior is consistent with mercantilist preferences, in which market access abroad is valued but domestic liberalization may not be. Why, then, should these governments view conflict as inducing opportunity costs? If they are sufficiently mercantilist, trade-disrupting conflict might improve their welfare, as it decreases the amount of competition facing domestic industries. Moreover, economic integration is rarely exogenously given. Governments that maintain trade policy autonomy can always choose the extent to which they participate in the global economy. This "endogenous" component of trade costs generates substantial trade frictions, even in today’s relatively globalized era [@Anderson2004; @Cooley2018].

The model developed here overcomes these analytical challenges by simultaneously modeling political bias, trade, and international conflict. It allows for domestic political processes to affect international relations, and for international bargaining to affect domestic policy outcomes. In the parlance of international relations theory, the model employs the analytical "second image" and "second image reversed" [@Waltz1959; @Gourevitch1978].^[@Lake2009b terms this paradigm "Open Economy Politics."] Employing the second image, the literature on "two-level games" [@Putnam1988; @Milner1997] and war links variation in domestic political institutions to variation in international conflict propensity [@Lake1992; @Snyder1993; @Schultz1998; @Solingen2014]. 

Because policy choices often generate international externalities, governments seek influence over the policy choices of other governments. Here, forces from abroad influence policy choice at home -- the second image reversed. Trade itself can be used as a form of leverage, if governments' welfare depends on market access or critical resources from abroad [@Hirschman1945]. Governments might also direct trade to minimize threats to their national security [@Gowa1993]. @Antras2011 analyze the effect of international interference in domestic political processes on trade policy. In the anarchy of world politics, such influence can always -– in principle -– take the form of threats, displays, or uses of military force [@Fearon1997]. This is the kind of influence analyzed here. @Bils2017 and @Krainin2018 have also considered models of bargaining and war in which the preference structure of the bargainers is more complex than the workhorse model of @Fearon1995.

The paper proceeds as follows. I first formalize the environment in which governments operate -- the international economy and the coercive bargaining setting. I then analyze this environment, formalizing the concepts of regime change and conflicts of interest along the way. This section concludes with the core Propositions (`` `r Pwar` `` and `` `r PeqTrade` ``) of the paper -- which maintain that low bias dyads trade more and fight less than their high bias counterparts. The connection between these propositions and the modern economic peace are discussed in the proceeding section. A final section concludes, discussing limitations of the argument and implications for the fields of international security and international political economy.