---
title: |
    | Gunboat Diplomacy
    | \tiny \hfill
    | \Large Political Bias, Trade Policy, and War
author:
	- name: Brendan Cooley
      affiliation: Ph.D. Candidate, Department of Politics, Princeton University
date: 13 November 2019
abstract: Countries with deep trading relationships rarely fight wars with one another. Here, I develop a theory of trade, war, and political bias, in which both trade and war are endogenous objects. Governments can rectify poor market access conditions abroad through war and subsequent regime change, in which the victorious country installs a liberal "puppet" government abroad. Trade policy bargaining is therefore conducted "in the shadow of power," with counterfactual wars shaping the policy choices that prevail in times of peace. When peace prevails, militarily weak countries are more open to trade than powerful ones, all else equal. Equilibrium trade policies balance domestic interests against military threats from abroad. War is less likely between liberal governments because they prefer less protectionist trade policies. As a result, trade flows and the probability of peace are positively correlated in equilibrium, even though trade does not cause peace.
thanks: Ph.D. candidate, Department of Politics, Princeton University. Previous versions of this paper were circulated under the titles "Trade Wars, Hot Wars, and the Commercial Peace" and "Trade Policy in the Shadow of Power." For helpful comments and discussions on earlier drafts of this paper, I thank Timm Betz, Adrien Bilal, Tyson Chatagnier, Rob Carroll, Andrew Coe, Noel Foster, Erik Gartzke, Kishore Gawande, Dan Gibbs, Joanne Gowa, Gene Grossman, Bobby Gulotty, Matias Iaryczower, Amanda Kennard, Colin Krainin, Melissa Lee, James Mao, Helen Milner, John Oneal, Kris Ramsay, Bryan Schonfeld, Brad Smith, Sondre Solstad, and Jack Zhang as well as audiences at Princeton's Political Economy Graduate Colloquium, Princeton's International Relations Graduate Seminar, Princeton's Fellowship of Woodrow Wilson Scholars, the Midwest Political Science Association's 2018 Annual Meeting, Southern Political Science Association's 2019 Annual Meeting, and the International Studies Association's 2019 Annual Meeting.
jelcodes: D72, D74, F13, F51, F52, F54

bibliography: /Users/bcooley/Dropbox (Princeton)/References/library.bib
biblio-style: apsr

papersize: letter
documentclass: article
geometry: margin=1.25in
link-citations: true

output:
	fig_caption: yes
    citation_package: natbib
    
---

```{r libs, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

knitr::opts_chunk$set(dev = 'pdf')

helperPath <- "source/R/"
helperFiles <- list.files(helperPath)
for (i in helperFiles) {
  source(paste0(helperPath, i))
}

libs <- c('tidyverse', "stargazer", "countrycode", "knitr", "ggrepel", "patchwork", "ggpubr", "padr", "latex2exp", "bibtex", "knitcitations")
ipak(libs)

# setup bib
mkdir("bib/")
file.copy("~/Dropbox (Princeton)/References/library.bib", "bib/library.bib", overwrite=TRUE)

# not available
Deeq <- "NA"
Dcoi <- "NA"
Dnceq <- "NA"
Dbeq <- "NA"

Aalpha <- "NA"
Aa <- "NA"
AwCosts <- "NA"

Pgamma <- "NA"
Pwar <- "NA"
Peeq <- "NA"
PeqTrade <- "NA"
PeqTau <- "NA"

Lqccv <- "NA"
Lpareto <- "NA"
LtildeTau <- "NA"
Lqccv <- "NA"
Ltauj <- "NA"
Lint <- "NA"

AddxEconomy <- "NA"
AddxEmpiricalFacts <- "NA"
AddxEconomy <- "NA"
AddxDefinitions <- "NA"

if (file.exists('references.RData')) load('references.RData')

# get helper functions
source('figs/source.R')

# get params
source('figs/params.R')

# setup definition, assumption, proposition, lemma tickers
Dtick <- 1
Atick <- 1
Ptick <- 1
Ltick <- 1

```

# Introduction

```{r, child = 'sections/introduction.rmd'}
```

# Environment

```{r, child="sections/model.rmd"}
```

# Analysis

```{r, child="sections/analysis.rmd"}
```

# Discussion

```{r, child="sections/discussion.rmd"}
```

# Conclusion

```{r, child="sections/conclusion.rmd"}
```

\clearpage

# Appendix

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

a <- 1
AddxEmpiricalFacts <- LETTERS[a]

```

## `r AddxEmpiricalFacts`: Trade, War, and Democracy: Empirical Facts

```{r, child="sections/Adata.rmd"}
```

\clearpage

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

a <- a + 1
AddxEconomy <- LETTERS[a]

```

## `r AddxEconomy`: International Economy

```{r, child="sections/Aeconomy.rmd"}
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

a <- a + 1
AddxDefinitions <- LETTERS[a]

```

## `r AddxDefinitions`: Constant Definitions

```{r, child="sections/AconstantDefs.rmd"}
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

a <- a + 1
AddxProofs <- LETTERS[a]

```

## `r AddxProofs`: Proofs

```{r, child="sections/Aproofs.rmd"}
```

\clearpage

# References

<div id="refs"></div>

# Software

```{r, echo=FALSE, warning=FALSE, message=FALSE, results="asis"}

save.image('references.RData')
# libs_all <- (.packages())
write_bib(file="bib/Rpackages.bib")
software_bib <- read.bib("bib/Rpackages.bib")
software_bib %>% sort()

```
